name: CI Pipeline Node/React

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # (Quitamos la línea de cache: 'npm' para evitar el error)

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar compilación (Build)
      run: npm run build